name: "Format code"

on:
  push:
    branches:
      - 'release-*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          src: "hugegraph-llm/src hugegraph-python-client/src"